# Generated by Django 4.2.6 on 2023-10-26 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('contacts', models.CharField(
                    max_length=100, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('number_house', models.CharField(
                    max_length=100, verbose_name='Номер дома')),
                ('name_product', models.CharField(
                    max_length=100, verbose_name='Название продукта')),
                ('model_product', models.CharField(
                    max_length=100, verbose_name='Модель')),
                ('date_exit_product', models.DateTimeField(
                    verbose_name='Дата выхода продукта')),
                ('creation_time',
                 models.CharField(default=django.utils.timezone.now,
                                  verbose_name='Время создания заявки')),
            ],
            options={
                'verbose_name': 'Базовый класс',
                'verbose_name_plural': 'Базовые классы',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('basemodel_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='market.basemodel')),
                ('supplier', models.CharField(default='Завод',
                 max_length=100, verbose_name='Поставщик')),
                ('debt', models.CharField(default=0, verbose_name='Задолженность')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
            bases=('market.basemodel',),
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('basemodel_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='market.basemodel')),
                ('debt', models.CharField(default=0, verbose_name='Задолженность')),
                ('supplier',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='market.factory',
                                   verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
            bases=('market.basemodel',),
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('basemodel_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='market.basemodel')),
                ('debt', models.CharField(default=0, verbose_name='Задолженность')),
                ('supplier',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='market.factory',
                                   verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
            bases=('market.basemodel',),
        ),
    ]
