# Generated by Django 4.2.6 on 2023-12-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Поставщик'),
        ),
    ]
